### ISSUE TITLE
This repo should point at the published paper

### ISSUE THREAD

**Issue by bethac07** [broadinstitute/cellpainting-gallery#96]
Because it's awesome :)

**Comment by ErinWeisbart** [comment]
Fixed with https://github.com/broadinstitute/cellpainting-gallery/commit/b379fbc8b756f959716c2b63bfef04db2d4812e4 and https://github.com/broadinstitute/cellpainting-gallery/commit/19e5c0f7921bac80c9de25312afb6f2dd63f40c9 and https://github.com/broadinstitute/cellpainting-gallery/commit/a9de7945255cbde969445a86a5fa90fcb62a112c


:)
